### ISSUE TITLE
Add Accessibility

### ISSUE THREAD

**Issue by greggles** [coloradodigitalservice/modern-software-delivery-maturity-index#11]
A suggestion from [mgifford](https://twitter.com/mgifford/status/1320332370906632192)

> They should add accessibility there.

Questions: Is that a top-level category or an element in an existing or new category? What category should it be?

**Comment by MatthewJMcAllister** [comment]
My take is that this should be added to the "user-centered design" row of the maturity index. Curious if @skcain you have a take on that?
